import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getPublishedArticleBySlug, listAllPublishedArticles } from '@/lib/xseek';

export const revalidate = 3600;
export const dynamicParams = true;

export async function generateStaticParams() {
  const articles = await listAllPublishedArticles();
  return articles.map((article) => ({ slug: article.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const article = await getPublishedArticleBySlug(slug);
  if (!article) return {};
  return {
    title: article.title,
    description: article.metaDescription ?? undefined,
  };
}

export default async function ArticlePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const article = await getPublishedArticleBySlug(slug);
  if (!article) notFound();

  const html = article.content ?? '';

  return (
    <main>
      <p>
        <Link href="/blog">← Back to blog</Link>
      </p>
      <article>
        <header>
          <h1>{article.title}</h1>
          {article.publishedAt && (
            <small style={{ color: '#9ca0ad' }}>
              Published {new Date(article.publishedAt).toLocaleDateString()}
            </small>
          )}
        </header>
        {/* xSeek returns sanitized HTML in `content`. If you want to render Markdown
            instead, use `article.contentMarkdown` and a renderer of your choice. */}
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </article>
      {article.schemaMarkup ? (
        <script
          type="application/ld+json"
          // JSON-LD generated by xSeek for richer SEO
          dangerouslySetInnerHTML={{ __html: JSON.stringify(article.schemaMarkup) }}
        />
      ) : null}
    </main>
  );
}
